# Generated by Django 2.2.6 on 2019-11-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20191109_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-timestamp',)},
        ),
    ]
